services:
  - type: web
    name: udaan-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://udaan-app.onrender.com
      - key: CORS_ORIGIN
        value: https://udaan-app.onrender.com

  - type: web
    name: udaan-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: VITE_API_URL
        value: https://udaan-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400