[build]
  base = "Backend"
  publish = "Backend"
  command = "npm install"

[functions]
  directory = "Backend"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/server.js"
  status = 200

[build.environment]
  NODE_VERSION = "18"